UNPACKD = unpackd.exe --files scripts
RMXP = "C:\Program Files (x86)\Enterbrain\RPGXP\RPGXP.exe"
NOHUP = cmd /c start

drun: unpackd.exe Game.exe
	$(UNPACKD) --combine --force && $(UNPACKD) --extract
	$(NOHUP) Game.exe debug

run: unpackd.exe Game.exe
	$(UNPACKD) --combine
	$(NOHUP) Game.exe

rmxp: unpackd.exe Game.rxproj
	$(UNPACKD) --combine
	$(NOHUP) $(RMXP) Game.rxproj

# dist: comming soon!
